<template>
  <div class="modal-header">
    <h2><span>Panel layout generator</span></h2>
    <button class="close icon-only-button" @click="store.showAbout = false">
      <XIcon />
    </button>
  </div>
  <div class="modal-body">
    <p>
      Welcome to Panel layout generator, a simple web application for generating
      a grid pattern of squares with user-defined colours and dimensions!
    </p>

    <p>
      With this app, you have the ability to create a customised grid of squares
      by specifying the number of columns and rows and selecting the colours
      you'd like to use. The app will generate the grid using your specified
      settings, with each square in the grid having a different colour than the
      squares to its sides or above and below it.
    </p>

    <p>
      To get started, simply input the desired number of columns and rows for
      your grid, as well as the colours you'd like to use. You must choose at
      least two colours, and the app will do its best to evenly distribute them
      throughout the grid. The grid will be generated immediately upon any of
      the inputs being changed, allowing you to easily modify and fine-tune your
      layout to your liking.
    </p>

    <p>
      In addition to generating the grid, you can also use the "Shuffle" button
      to randomly rearrange the colours of the squares in the grid. This is a
      great way to mix things up and try out new colour combinations.
    </p>

    <p>
      One of the primary purposes of Panel layout generator is to assist
      acoustic panel installers in creating a layout for their installations.
      With the ability to customize the number of columns and rows and select
      from a range of colours, installers can easily plan out the placement of
      panels in a visually appealing and functional manner.
    </p>

    <p>
      We hope you enjoy using Panel layout generator for generating colourful
      grid patterns. Happy creating!
    </p>
    <p class="generation-info">[ This about page was generated by ChatGPT ]</p>
    <hr />
    <h3>License <ScaleIcon /></h3>
    <p>
      This project is licensed under the
      <a href="https://github.com/ryan-voitiskis/crate-guide/blob/main/LICENSE">
        MIT License
      </a>
    </p>
    <h3>Contributions <PullRequestIcon /></h3>
    <p>
      <a href="https://github.com/ryan-voitiskis/panel-layout-generator"
        >Panel layout generator</a
      >
      is an open source project, contributions are welcome.
    </p>
    <h3>Author <CodeIcon /></h3>
    <p>
      Created and maintained by Ryan Voitiskis. Please email me feedback or
      suggestions.
    </p>
    <p class="last-p">
      <a href="mailto:ryanvoitiskis@pm.me">ryanvoitiskis@pm.me</a> |
      <a href="https://github.com/ryan-voitiskis">GitHub</a>
    </p>
  </div>
  <div class="modal-footer">
    <button class="close" @click="store.showAbout = false">Close</button>
  </div>
</template>

<script setup lang="ts">
import XIcon from "../components/icons/XIcon.vue"
import { matrixStore } from "../matrixStore"
import ScaleIcon from "../components/icons/ScaleIcon.vue"
import PullRequestIcon from "../components/icons/PullRequestIcon.vue"
import CodeIcon from "../components/icons/CodeIcon.vue"

const store = matrixStore()
</script>

<style lang="scss">
.modal-body > p.generation-info {
  color: #888;
  text-align: center;
}
h2 {
  span {
    font-size: 28px;
    font-weight: 600;
    line-height: 38px;
    background: linear-gradient(
      96.2deg,
      rgb(207, 185, 71) 10.4%,
      rgb(255, 100, 100) 43.8%,
      rgb(0, 93, 219) 105.8%
    );
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    display: inline-block;
  }
}

hr {
  margin-bottom: 30px;
}
h3 {
  display: flex;
  align-content: center;
  svg {
    align-self: center;
    height: 22px;
    margin-left: 10px;
  }
}

@media print {
  html {
    background-color: white;
  }
}
</style>
