<template>
  <div class="modal-header">
    <h2>About Panel Layout Generator</h2>
    <button class="close icon-only-button" @click="store.showAbout = false">
      <XIcon />
    </button>
  </div>
  <div class="modal-body">
    <p>
      Welcome to our simple JavaScript web application for generating a grid
      pattern of squares with user-defined colours and dimensions!
    </p>

    <p>
      With this app, you have the ability to create a customised grid of squares
      by specifying the number of columns and rows and selecting the colours
      you'd like to use. The app will then generate the grid using your
      specified settings, with each square in the grid having a different colour
      than the squares to its sides or above and below it.
    </p>

    <p>
      To get started, simply input the desired number of columns and rows for
      your grid, as well as the colours you'd like to use. You can choose as
      many or as few colours as you'd like, and the app will do its best to
      evenly distribute them throughout the grid. The grid will be generated
      immediately upon any of the inputs being changed, allowing you to easily
      modify and fine-tune your grid to your liking.
    </p>

    <p>
      In addition to generating the grid, you can also use the "Shuffle" button
      to randomly rearrange the colours of the squares in the grid. This is a
      great way to mix things up and try out new colour combinations.
    </p>

    <p>
      One of the primary purposes of this app is to assist acoustic panel
      installers in creating a layout for their installations. With the ability
      to customize the number of columns and rows and select from a range of
      colours, installers can easily plan out the placement of panels in a
      visually appealing and functional manner.
    </p>

    <p>
      We hope you enjoy using our simple JavaScript web application for
      generating colourful grid patterns. Happy creating!
    </p>
    <hr />
    <p class="generation-info">This about page was generated by ChatGPT.</p>
  </div>
  <div class="modal-footer">
    <button class="close" @click="store.showAbout = false">Close</button>
  </div>
</template>

<script setup lang="ts">
import XIcon from "../components/icons/XIcon.vue"
import { matrixStore } from "../matrixStore"
const store = matrixStore()
</script>

<style lang="scss">
.modal-body > p.generation-info {
  color: #777;
  text-align: center;
}

@media print {
  html {
    background-color: white;
  }
}
</style>
